cat > config.yaml <<EOF
log_file: logs/main_log.log

data:
  path: data/raw/opiod_raw_data.csv
  file_type: csv

validation:
  schema:
    OD: int
    Low_inc: int
    Surgery: int
    rx_ds: float
    A-V: int

preprocessing:
  scaler: StandardScaler

model:
  type: RandomForestClassifier
  params:
    n_estimators: 100
    random_state: 42

target_column: OD

artifacts: models/
EOF