name: cancer-classification
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - openpyxl>=3.0.0  # For reading Excel files
  - pyyaml>=5.4.0
  - joblib>=1.1.0
  - pip:
    - pytest>=7.0.0  # For testing
    - black>=22.0.0  # For code formatting
    - flake8>=4.0.0  # For linting 