name: data_loader

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pandas
  - hydra-core
  - omegaconf
  - python-dotenv
  - pyyaml
  - openpyxl
  - pip
  - pip:
      - wandb