name: inference
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pandas            # for DataFrame I/O
  - numpy             # for numerical arrays
  - scikit-learn      # for your BaseEstimator imports
  - hydra-core        # for @hydra.main
  - omegaconf         # for DictConfig / OmegaConf
  - python-dotenv     # load_dotenv
  - pyyaml            # for yaml.safe_load / yaml.dump
  - openpyxl          # for read_excel / to_excel
  - pip
  - pip:
    - wandb           # W&B client
