data_source:
  path: "./data/raw/cancer.xlsx"   # Relative or absolute path to data file (update as needed)
  type: "excel"                    # Data file type: 'csv' or 'excel'
  sheet_name: "Sheet1"             # Only used if type == 'excel'
  header: 0                        # Row number to use as column names (0-indexed), update if needed
  encoding: "utf-8"                # File encoding (utf-8 covers most cases)

logging:
  level: INFO
  log_file: ./logs/main.log
  format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s'
  datefmt: '%Y-%m-%d %H:%M:%S'

data_split:
  test_size: 0.2
  valid_size: 0.2
  random_state: 42

model:
  active: random_forest
  random_forest:
    save_path: models/random_forest.pkl
    params:
      n_estimators: 100
      max_depth: 10
      random_state: 42
