data_source:
  raw_path: "./data/raw/cancer.xlsx"   
  processed_path: "./data/processed/cancer_processed.xlsx"   
  type: "excel"                    # Data file type: 'csv' or 'excel'
  sheet_name: "Sheet1"             # Only used if type == 'excel'
  header: 0                        # Row number to use as column names (0-indexed), update if needed
  encoding: "utf-8"                # File encoding (utf-8 covers most cases)

logging:
  level: INFO
  log_file: ./logs/main.log
  format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s'
  datefmt: '%Y-%m-%d %H:%M:%S'

data_split:
  test_size: 0.2
  valid_size: 0.2
  random_state: 42

model:
  type: "knn"  # Type of model to use
  params:
    n_neighbors: 5
    metric: cosine
    random_state: 42

target: target

raw_features:
  - mean radius
  - mean texture
  - mean perimeter
  - mean area
  - mean smoothness
  - mean compactness
  - mean concavity
  - mean concave points
  - mean symmetry
  - mean fractal dimension
  - radius error
  - texture error
  - perimeter error
  - area error
  - smoothness error
  - compactness error
  - concavity error
  - concave points error
  - symmetry error
  - fractal dimension error
  - worst radius
  - worst texture
  - worst perimeter
  - worst area
  - worst smoothness
  - worst compactness
  - worst concavity
  - worst concave points
  - worst symmetry
  - worst fractal dimension

artifacts:
  preprocessing_pipeline: "models/preprocessing_pipeline.pkl"
  model_path: "models/active_model.pkl"

data_validation:
  enabled: true
  action_on_error: "raise"        # "raise" or "warn"
  report_path: "logs/validation_report.json"
  schema:
    columns:
      - name: "id"
        dtype: "int"
        required: true
        min: 0
      - name: "mean radius"
        dtype: "float"
        required: false
        min: 0.0
      - name: "mean texture"
        dtype: "float"
        required: false
        min: 0.0
      - name: "mean perimeter"
        dtype: "float"
        required: false
        min: 0.0
      - name: "mean area"
        dtype: "float"
        required: false
        min: 0.0
      - name: "mean smoothness"
        dtype: "float"
        required: false
        min: 0.0
      - name: "mean compactness"
        dtype: "float"
        required: false
        min: 0.0
      - name: "mean concavity"
        dtype: "float"
        required: false
        min: 0.0
      - name: "mean concave points"
        dtype: "float"
        required: false
        min: 0.0
      - name: "mean symmetry"
        dtype: "float"
        required: false
        min: 0.0
      - name: "mean fractal dimension"
        dtype: "float"
        required: false
        min: 0.0
      - name: "radius error"
        dtype: "float"
        required: false
        min: 0.0
      - name: "texture error"
        dtype: "float"
        required: false
        min: 0.0
      - name: "perimeter error"
        dtype: "float"
        required: false
        min: 0.0
      - name: "area error"
        dtype: "float"
        required: false
        min: 0.0
      - name: "smoothness error"
        dtype: "float"
        required: false
        min: 0.0
      - name: "compactness error"
        dtype: "float"
        required: false
        min: 0.0
      - name: "concavity error"
        dtype: "float"
        required: false
        min: 0.0
      - name: "concave points error"
        dtype: "float"
        required: false
        min: 0.0
      - name: "symmetry error"
        dtype: "float"
        required: false
        min: 0.0
      - name: "fractal dimension error"
        dtype: "float"
        required: false
        min: 0.0
      - name: "worst radius"
        dtype: "float"
        required: false
        min: 0.0
      - name: "worst texture"
        dtype: "float"
        required: false
        min: 0.0
      - name: "worst perimeter"
        dtype: "float"
        required: false
        min: 0.0
      - name: "worst area"
        dtype: "float"
        required: false
        min: 0.0
      - name: "worst smoothness"
        dtype: "float"
        required: false
        min: 0.0
      - name: "worst compactness"
        dtype: "float"
        required: false
        min: 0.0
      - name: "worst concavity"
        dtype: "float"
        required: false
        min: 0.0
      - name: "worst concave points"
        dtype: "float"
        required: false
        min: 0.0
      - name: "worst symmetry"
        dtype: "float"
        required: false
        min: 0.0
      - name: "worst fractal dimension"
        dtype: "float"
        required: false
        min: 0.0
      - name: "target"
        dtype: "int"
        required: true
        allowed_values: [0,1]