name: mlops_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - joblib
  - numpy
  - pandas
  - pytest
  - python-dotenv
  - pyyaml
  - scikit-learn
  - sqlalchemy
  - requests
  - openpyxl
  - pip
  - dvc
  - dvc-s3
  - awscli
  - boto3=1.35
  - botocore=1.35
  - s3fs=2024.3
  - pip:
    - pytest-cov
    - pykernel
    - flake8
    - mlflow
    - mlflow-skinny
    - fastapi
