name: mlops_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - joblib
  - numpy
  - pandas
  - pytest
  - python-dotenv
  - pyyaml
  - scikit-learn
  - sqlalchemy
  - requests
  - openpyxl
  - pip
  - pip:
    - pytest-cov
    - pykernel
    - flake8
